<!DOCTYPE html>
<html>
    <head>
        <title>
            API request(usage of a promise thru a 3rd party package called "axios")
        </title>
    </head>
    <body>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.7.7/axios.min.js"></script>
        <script>
            const url='https://jsonplaceholder.typicode.c/users'

            // //=================working with axios(3rd party package) - consuming  
            // axios.get(url)
            //         .then((response)=>{//if its successfull consumption of data then .then be called 
            //             const users=response.data
            //             console.log(users)
            //         })
            //         .catch((err)=>{
            //             console.log(err.message)//if url is wrong above then error will be caught using this line .catch
            //         })
            //=====================

            //===============Working wiht our own axios(miniature functionality) - promise producing and consuming
            //======producing code
            const myAxios = {
                get: function(url){ //once data from abover server/url - resolve get called else reject will called
                    const promiseObj = new Promise((resolve, reject)=>{ //creation of promise obj //wn any asyncronous function to be done it is written inside this call back fnctn
                        const xhr= new XMLHttpRequest()
                        xhr.open('GET', url)
                        xhr.send()
                        xhr.onload=function(){
                            const data= JSON.parse(xhr.responseText) 
                            
                            resolve(data)
                        }
                        xhr.onerror = function(){
                            //reject(xhr.responseText) //if above url is proper then we get data in that server and will have access thru responseText but if url is wrong then the it will be a empty string so no error be writter hence will raise the new error below
                            reject(new Error('something went wrong'))
                        }
                    })
                    return promiseObj  //returning same promiseobj  
                }
            }   

            //consuming code
            myAxios.get(url) //wnver we use axios.get/post/put/delete then it returns a promise object
                 .then((response)=>{
                    console.log(response)
                 })
                 .catch((err)=>{
                    console.log(err)
                 })
        </script>
    </body>
</html>